// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBOFYk23kK8PcTj175wOevEtWw_7dI6Aw',
    appId: '1:380566732256:web:ccb2cb209dae7f3c76bf85',
    messagingSenderId: '380566732256',
    projectId: 'wallet-application-dc6ae',
    authDomain: 'wallet-application-dc6ae.firebaseapp.com',
    storageBucket: 'wallet-application-dc6ae.firebasestorage.app',
    measurementId: 'G-15ZFHZD3QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRzFaKSgHTkAUAdbu-lZhJrGLpeaO90KM',
    appId: '1:380566732256:android:124be1e35d095c4576bf85',
    messagingSenderId: '380566732256',
    projectId: 'wallet-application-dc6ae',
    storageBucket: 'wallet-application-dc6ae.firebasestorage.app',
  );
}
