/// On-device AI categorization engine.
/// Uses keyword-based NLP to classify transactions into spending categories.
class AiCategorizationService {
  AiCategorizationService._();

  static const Map<String, List<String>> _keywords = {
    'Dining': [
      'swiggy',
      'zomato',
      'restaurant',
      'cafe',
      'food',
      'pizza',
      'burger',
      'biryani',
      'dinner',
      'lunch',
      'breakfast',
      'dominos',
      'mcdonalds',
      'kfc',
      'starbucks',
    ],
    'Transport': [
      'uber',
      'ola',
      'rapido',
      'metro',
      'bus',
      'fuel',
      'petrol',
      'diesel',
      'toll',
      'parking',
      'cab',
      'auto',
      'train',
      'flight',
      'irctc',
    ],
    'Shopping': [
      'amazon',
      'flipkart',
      'myntra',
      'ajio',
      'mall',
      'store',
      'shop',
      'retail',
      'purchase',
      'buy',
      'meesho',
      'nykaa',
    ],
    'Bills': [
      'electricity',
      'water',
      'gas',
      'internet',
      'broadband',
      'wifi',
      'rent',
      'emi',
      'insurance',
      'tax',
      'postpaid',
      'prepaid',
      'recharge',
      'dth',
    ],
    'Entertainment': [
      'netflix',
      'spotify',
      'hotstar',
      'prime',
      'movie',
      'theatre',
      'gaming',
      'playstation',
      'steam',
      'youtube',
      'subscription',
    ],
    'Finance': [
      'investment',
      'mutual fund',
      'stock',
      'sip',
      'fd',
      'loan',
      'credit',
      'emergency',
      'deposit',
      'interest',
    ],
    'Health': [
      'hospital',
      'doctor',
      'medicine',
      'pharmacy',
      'medical',
      'gym',
      'fitness',
      'health',
      'apollo',
      'practo',
    ],
    'Education': [
      'course',
      'udemy',
      'college',
      'school',
      'tuition',
      'books',
      'exam',
      'fees',
      'university',
      'coaching',
    ],
    'Groceries': [
      'grocery',
      'bigbasket',
      'blinkit',
      'zepto',
      'instamart',
      'vegetables',
      'fruits',
      'milk',
      'dmart',
      'supermarket',
    ],
    'Savings': ['save', 'vault', 'round-up', 'auto-save', 'piggy', 'savings'],
    'Transfers': [
      'transfer',
      'top-up',
      'topup',
      'sent to',
      'received',
      'upi',
      'neft',
      'imps',
      'rtgs',
      'salary',
    ],
  };

  /// Categorize a single transaction title.
  static String categorize(String title) {
    final lower = title.toLowerCase();
    for (final entry in _keywords.entries) {
      for (final keyword in entry.value) {
        if (lower.contains(keyword)) return entry.key;
      }
    }
    return 'Other';
  }
}
